name: Release

on:
  push:
    branches: 
      - main
      - dev
      - canary

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits --force
      working-directory: ./.github/workflows

    - name: NPM Install
      run: npm ci

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GIT_AUTHOR_NAME: pksorensen
        GIT_AUTHOR_EMAIL: poul@kjeldager.com
      run: npm run release